version: "3.8"
services:
  auth:
    container_name: auth
    build: ./auth/
    ports:
      - "8002:8080"
    environment:
      DD_DB_HOST: db
    command: /auth
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: goland
      POSTGRES_PASSWORD: goland
      POSTGRES_DB: goland
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql